"""
This is a py2app.py script generated by py2applet

Usage:
    python py2app.py py2app -p nought
"""

#
import os
from setuptools import setup

APP = ['nought/NoughtInstaller.py']
DATA_FILES = []
OPTIONS = {
    'iconfile':'icon.icns',
    'plist': {'CFBundleShortVersionString':os.getenv("VERSION"),}
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
