"""
This is a setup.py script generated by py2applet

Usage:
    python py2app.py py2app -p nought
"""

#

from setuptools import setup

APP = ['nought/mac.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
